# This is a basic workflow to help you get started with Actions

name: download-artifact

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      remote:
        required: true
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [arm64]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set env.HOME to $HOME
        run: echo "HOME=$HOME" >> $GITHUB_ENV
        shell: bash

      #- name: Creating cache folder on /dev/disk/azure/resource-part1 (SSD)
      #  run: |
      #    mkdir -p $HOME/cache

      - name: Creating cache folder on /dev/disk/azure/resource-part1 (SSD)
        run: |
          sudo mkdir -p /mnt/cache
          sudo chown -R runner:docker /mnt/cache
          
      - name: Creating symlink in $HOME/cache pointing to cache on /dev/disk/azure/resource-part1
        run: ln -s /mnt/cache $HOME/

      - name: download last cache
        uses: qmwd2006/actions-download-artifact@master
        with:
          workflow: download-artifact.yml
          name: kiwibrowser-ccache-${{ matrix.platform }}.tar.gz
          path: ${{env.HOME}}/
          branch: master
          workflow_conclusion: success; timed_out; failure

      - name: untar cache
        run: |
          # ls -R $HOME
          tar -zxvf $HOME/cache.tar.gz -C $HOME/cache
          rm -rf $HOME/cache.tar.gz
          # tree $HOME/cache

      - name: gen a file in cache
        if: always()
        run: |
          touch $HOME/cache/.gitignore
          echo hello>$HOME/cache/$(date "+%Y%m%d-%H%M%S").txt
          tree $HOME/cache/

      - name: tar cache
        if: always()
        run: |
          tar -zcvf $HOME/cache.tar.gz -C $HOME/cache .
          du -sh $HOME/cache.tar.gz

      - name: Uploading binary objects to cache
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: kiwibrowser-ccache-${{ matrix.platform }}.tar.gz
          path: ~/cache.tar.gz
          retention-days: 2

      - name: download last cache again
        uses: qmwd2006/actions-download-artifact@master
        with:
          workflow: download-artifact.yml
          name: kiwibrowser-ccache-${{ matrix.platform }}.tar.gz
          path: ${{env.HOME}}/

      - name: untar cache
        run: |
          # ls -R $HOME
          rm -rf $HOME/cache/*
          tar -zxvf $HOME/cache.tar.gz -C $HOME/cache
          rm -rf $HOME/cache.tar.gz
          # tree $HOME/cache

      - name: Setup Debug Session
        if: ${{ github.event.inputs.remote == 'true' }}
        uses: csexton/debugger-action@master
